### ISSUE TITLE
Event node does not accept "priority = 0"

### ISSUE THREAD

**Issue by tjvandam** [SmartParksOrg/node-red-contrib-earthranger#6]
Priority can be:
RED = 300
AMBER = 200
GREEN = 100
GREY = 0
However the Event node turns any other value the 200 or 100 into 300 (RED). 

Solutions: GREY needs to be added as a valid option and should be the default as stated in the documentation.

**Comment by adminfriso** [comment]
on this line looks like it does accept 0 or else a val beteween 100 and 300
https://github.com/SmartParksOrg/node-red-contrib-earthranger/blob/ad047312dd038c1afd70abd301c3ecb1b71a0f9c/src/nodes/er-send-event/er-send-event.ts#L99

**Comment by adminfriso** [comment]
tested on call, this response of 300 comes from the Earth ranger api. its based on the event type default priority value
