### ISSUE TITLE
Parsing invalid JSON causes NodeRED crash

### ISSUE THREAD

**Issue by tsuijten** [SmartParksOrg/node-red-contrib-earthranger#7]
Here a JSON response is assumed, when (for whatever reason) a different response is given NodeRED crashes entirely. 

https://github.com/SmartParksOrg/node-red-contrib-earthranger/blob/dev/src/nodes/earthranger-connection/earthranger-connection.ts#L51

We can see this in the following logs:
```
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]: 27 Mar 11:38:47 - [red] Uncaught Exception:
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]: 27 Mar 11:38:47 - [error] SyntaxError: Unexpected token < in JSON at position 0
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]:     at JSON.parse (<anonymous>)
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]:     at IncomingMessage.<anonymous> (/root/.node-red/node_modules/@smartparks/node-red-contrib-earthranger/dist/nodes/earthranger-connection/earthranger-connection.js:33:34)
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]:     at IncomingMessage.emit (node:events:539:35)
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]:     at endReadableNT (node:internal/streams/readable:1345:12)
Mar 27 11:38:47 smartparks-gonarezhou Node-RED[1108008]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The fix would be to surround the `JSON.parse(str)` in a `try/catch` block and fail gracefully. The same goed for this: https://github.com/SmartParksOrg/node-red-contrib-earthranger/blob/dev/src/nodes/earthranger-connection/earthranger-connection.ts#L106

**Comment by adminfriso** [comment]
agreed upon suggestion and tested it in the lastest commit. will be released in 1.3.3
